trainer:
  max_epochs: 32
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
model:
  class_path: training.linear_semantic.LinearSemantic
  init_args:
    network:
      class_path: models.linear_decoder.LinearDecoder
data:
  class_path: datasets.ade20k.ADE20K